### ISSUE TITLE
Wrong keybinding for US keyboards playing TOTD2

### ISSUE THREAD

**Issue by Courbo** [p1pkin/demul#497] opened 2020-06-09 07:05 UTC
So most of the keys work for the keyboard playing Typing of the Dead 2. But, some of the keys are messed up and can't continue. It is properly setup with maple, but here are some of the keys that are bugged.

The keys that are messed up are: ' and , and right Shift
, comes up as m.
' doesn't even register as a key.
Right Shift doesn't even come up either

I have been trying to find some key bindings or config files to edit and figure out whats causing this but i'm able to find it. Also my understanding of coding is limited so i was wondering any plugins or fixes that could be viable to changing the mapping of the keyboard or just finding the keyboard output.

**Comment by p1pkin** [comment] 2020-06-10 02:02
probably duplicate of #170 
technically it was already fixed few years ago, should be ok in next public release

**Closed as completed** 2023-03-14 03:57 UTC
