### ISSUE TITLE
sound bug issue for Dr. Doom for Marvel vs. Capcom 2: New Age of Heroes Naomi 

### ISSUE THREAD

**Issue by jmodlin210** [p1pkin/demul#440] opened 2017-11-18 15:06 UTC
When i was playing Dr. Doom for Marvel vs. capcom 2: new age of heroes naomi to switch the partner, there was a sound bug for Doctor Doom not there when using another partner.

**Comment by p1pkin** [comment] 2017-11-18 18:07
looks like some regression, thanks
caused by r3892

**Comment by jmodlin210** [comment] 2017-11-18 19:39
How can we fix the sound bug  of when playing Dr. Doom for Marvel vs. Capcom 2: New age of heroes naomi to switch the partner for DEMUL?

**Comment by p1pkin** [comment] 2017-11-18 19:42
as temp solution you may switch to older version, like 160818

**Comment by jmodlin210** [comment] 2017-11-18 19:44
I like to stick to new versions. I want the sound bug to be fixed of when playing Dr. Doom for Marvel vs. Capcom 2: New Age of Heroes Naomi to switch to partner in the next update.

**Comment by p1pkin** [comment] 2017-11-18 19:47
sure, but there is no way to avoid this issue in latest version, will be fixed in next one.

quite interesting AICA Envelope Generator usage test case btw.

**Comment by jmodlin210** [comment] 2017-11-18 19:49
what does AICA Envelope Generator test case mean? did you say that the issue of the sound bug to be fixed of when playing Dr. Doom for Marvel vs. Capcom 2: New Age of Heroes NAOMI to switch to partner in the next update?

**Comment by p1pkin** [comment] 2017-11-21 17:26
simply speaking, this issue revealed old standing design flaw in sound emulation, which happen in rare "edge cases".
anyway, it was fixed in current code, will be fine in some next public build.

**Comment by Enio-Perceval** [comment] 2018-02-13 02:56
Anakaris has a Naomi sound glitch too! It's some kind of infinite feedback of his spell, very similar to Doctor Doom's infinite "jet" sound feedback.

**Closed as completed** 2018-04-26 15:35 UTC
