### ISSUE TITLE
18wheelers and waverunner controls

### ISSUE THREAD

**Issue by xbrunox76** [p1pkin/demul#446] opened 2018-01-28 08:54 UTC
cant find Reverse key in 18whellers and throttle keys in waverunner.
i've set all in demul player1 arcade controls options, all digital and all analog keys, but in game test menu, input test,  nothing fot that controls seems to work.

**Comment by p1pkin** [comment] 2018-01-29 08:34
please create single issue for single problem.
1. 18 Wheeler (Naomi): cant reproduce it here. analog 1 UP works as accelerator pedal, as it should.
2.  Wave Runner GP: there is a bug in Throttle pedal handling, it works only if analog axis mapped to it, doesn't work if playing from keyboard. will be fixed in next release.

**Comment by xbrunox76** [comment] 2018-01-29 10:23
Hi sorry for 2 issue in one post.
1. in 18 wheeler the accelerator works well. the problem is the R gear. i cant find the key. i have only digital controls, but I map analog to digital.

2. I map analog to digital controls i'll wait for the next release.

**Comment by p1pkin** [comment] 2018-01-29 10:52
got it now. gearbox lever is not simulated, to enable R gear need to hold buttons 2 and 3.

**Closed as completed** 2018-04-26 15:34 UTC
