### ISSUE TITLE
Feature Request: Ability to set button for Pause/Resume

### ISSUE THREAD

**Issue by cooljeffro** [p1pkin/demul#395] opened 2016-11-21 09:04 UTC
I am using Demul to play Initial D with a logitech steering wheel. I would like to be able to pause/resume the game with a button instead of using the mouse to go into the File menu and choosing pause/resume.  This way I can pause in the middle of a race without taking my hands off the steering wheel.

**Comment by p1pkin** [comment] 2016-11-21 19:03
you can use Pause/Break on keyboard

duplicate of https://github.com/p1pkin/demul/issues/57

**Closed as completed** 2016-11-21 19:05 UTC
Labels: duplicate
